### PR TITLE
update grammar for swift 3.0

### PR DESCRIPTION
**Pull request by litt1e-p**
hello wangchn, I have used WMPageController for a long time, now I found this swift version which I will use in my new project. It show some warnings because of old swift grammar. so I change it with swift 3.0 recommended. May I make a PR for it?

### CODE REVIEW

**Comment by wangmchn** [comment]
Thanks a lot! 😃

**Comment by litt1e-p** [comment]
you did a great job.thx. will it support Carthage in future?

2016年4月18日星期一，Wang Ming notifications@github.com 写道：

**Comment by wangmchn** [comment]
Yes, try it soon~ : )

**Comment by litt1e-p** [comment]
great! I will wait for you

2016年4月18日星期一，Wang Ming notifications@github.com 写道：

**Pull request merged**
